name: Sikar News Bot

on:
  schedule:
    - cron: '0 */2 * * *' # Runs every 2 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install aiohttp beautifulsoup4 python-telegram-bot

      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CH_ID: ${{ secrets.CH_ID }}
        run: python main.py

      - name: Commit History
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posted_sikar_news.txt
          git commit -m "Update history [skip ci]" || exit 0
          git push
