name: Sikar News Bot

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install aiohttp beautifulsoup4 python-telegram-bot

      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CH_ID: ${{ secrets.CH_ID }}
          LINKVERTISE_ID: ${{ secrets.LINKVERTISE_ID }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add posted_sikar_news.txt
          git commit -m "Update posted news history [skip ci]" || echo "No changes to commit"
          git push
